/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rensis.rensisfit;
import at.favre.lib.crypto.bcrypt.BCrypt;
import com.rensis.data.DataAccess;
import com.rensis.models.Usuari;
import com.rensis.styles.*;

/**
 *
 * @author Wilde
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainAppFrame
     */
    
    private UserPanel userPanel;

    
    public MainScreen() {
        initComponents();
        
        // Styling the components borders
        loginButton.setBorder(UIStyles.DEFAULT_BORDER_3PX);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        mainIcon = new javax.swing.JLabel();
        webLink = new javax.swing.JLabel();
        loginButton = new RoundedButton("");
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startPanel.setBackground(new java.awt.Color(255, 255, 255));

        mainIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/480x125.png"))); // NOI18N

        webLink.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        webLink.setForeground(new java.awt.Color(51, 102, 255));
        webLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLink.setText("rensisfit.rensis.com");

        loginButton.setBackground(new java.awt.Color(230, 230, 230));
        loginButton.setFont(UIStyles.getFont(48)
        );
        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Login");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusable(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                            .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mainIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                                .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(388, 388, 388))
                        .addGroup(startPanelLayout.createSequentialGroup()
                            .addComponent(webLink, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(mainIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webLink)
                .addGap(143, 143, 143)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        // Create an login dialog form and set visible
        LoginForm loginDialog = new LoginForm(this, true);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel mainIcon;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel webLink;
    // End of variables declaration//GEN-END:variables
    
    // Login handler
    public void loginHandler(String mail, char[] password){
    
        // Getting user with email
        Usuari user = DataAccess.getUser(mail);
        
        // Getting password hash from de database
        String passwordHash = user.getPasswordHash();
        
        // Check if password hash is not null (if user is not found on the database passwordHash will be null)
        if (passwordHash != null){
            
            // User need to be an instructor
            if(user.isInstructor()){
                
                // Checking the password
                if(BCrypt.verifyer().verify(password, passwordHash).verified){

                    // Cleaning the error label
                    errorLabel.setText("");
                    
                    // Setting up the user panel on our frame
                    startPanel.setVisible(false);
                    userPanel = new UserPanel(this,user);
                    userPanel.setBounds(0,0,1280,720);
                    userPanel.setVisible(true);

                    // Adding userPanel to our frame
                    getContentPane().add(userPanel);

                } else {
                    // Error label for wrong password
                    errorLabel.setText("Wrong password");
                }
                //endif
                
            } else {
                // Error label if the user is not an instructor
                errorLabel.setText("Access denied: User is not an instructor");
            }
            //endif
            
        } else {
            // Error laber if the user was not found
            errorLabel.setText("User not found");
        }
        //endif
            
    }
    
    // Logout handler
    public void logoutHandler(){
        startPanel.setVisible(true);
        userPanel = null;
    }

}
